[package]
name = "xtensa-lx6-rt"
version = "0.2.0"
description = "Low level access for xtensa lx6 processors"
categories = ["embedded", "hardware-support", "no-std"]
keywords = ["xtensa", "lx6", "register", "peripheral"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/esp-rs/xtensa-lx6-rt"
authors = [
    "Scott Mabin <scott@mabez.dev>", 
    "Arjan Mels <arjan@mels.email>",
]
edition = "2018"
links = "xtensa-lx6-rt" # prevent multiple versions of this crate to be linked together

[dependencies]
r0 = "1.0.0"
bare-metal = { version = "0.2.0", features = ["const-fn"] }
xtensa-lx6-rt-proc-macros = { path = "procmacros" }